/* ============================================================
 *  Player entity
 * ============================================================
 *  Handles:
 *    - left/right movement (A/D or ←/→)
 *    - jumping (W / ↑ / Space) when on the ground
 *    - gravity + collision (arcade physics, handled in the scene)
 *
 *  Tuning values live at the top so they're easy to tweak.
 * ============================================================ */

const PLAYER_CONFIG = {
  moveSpeed: 220,       // horizontal pixels/sec
  jumpVelocity: -460,   // negative = up
  dragX: 1400,          // slows down when no input
};

class Player {
  constructor(scene, x, y) {
    this.scene = scene;

    // Create the sprite using the texture generated by AssetLoader.
    this.sprite = scene.physics.add.sprite(x, y, ASSETS.player.key);
    this.sprite.setScale(ASSETS.player.scale);
    this.sprite.setCollideWorldBounds(true);
    this.sprite.setDragX(PLAYER_CONFIG.dragX);
    this.sprite.setMaxVelocity(PLAYER_CONFIG.moveSpeed, 1000);

    // Input bindings — both WASD and arrow keys supported.
    this.cursors = scene.input.keyboard.createCursorKeys();
    this.keys = scene.input.keyboard.addKeys({
      left:  Phaser.Input.Keyboard.KeyCodes.A,
      right: Phaser.Input.Keyboard.KeyCodes.D,
      up:    Phaser.Input.Keyboard.KeyCodes.W,
    });
  }

  update() {
    const body = this.sprite.body;
    const leftDown  = this.cursors.left.isDown  || this.keys.left.isDown;
    const rightDown = this.cursors.right.isDown || this.keys.right.isDown;
    const jumpDown  = this.cursors.up.isDown    || this.keys.up.isDown || this.cursors.space.isDown;

    // Horizontal movement — set velocity directly for snappy platformer feel.
    if (leftDown && !rightDown) {
      this.sprite.setVelocityX(-PLAYER_CONFIG.moveSpeed);
    } else if (rightDown && !leftDown) {
      this.sprite.setVelocityX(PLAYER_CONFIG.moveSpeed);
    }
    // (no-input case: dragX decelerates naturally)

    // Jump only when touching the ground.
    if (jumpDown && body.blocked.down) {
      this.sprite.setVelocityY(PLAYER_CONFIG.jumpVelocity);
    }
  }

  // Used by project objects to measure "nearby" distance.
  getPosition() {
    return { x: this.sprite.x, y: this.sprite.y };
  }
}

window.Player = Player;
