/* ============================================================
 *  Player entity — movement logic only
 * ============================================================
 *  Reads config from PhysicsConfig and input from InputSystem.
 *  Responsible for:
 *    - acceleration-based horizontal movement (Terraria feel)
 *    - strong ground friction, reduced air control
 *    - snappy jump + variable jump height (release early = shorter)
 *    - double jump with proper state reset
 *    - coyote time + jump buffer (tiny grace windows)
 *
 *  No physics constants live here — tweak them in
 *  /systems/physicsSystem.js.
 * ============================================================ */

class Player {
  constructor(scene, x, y, input) {
    this.scene = scene;
    this.input = input;

    // Create the sprite (texture generated by AssetLoader).
    this.sprite = scene.physics.add.sprite(x, y, ASSETS.player.key);
    this.sprite.setScale(ASSETS.player.scale);
    this.sprite.setCollideWorldBounds(true);
    // Clamp horizontal speed defensively (we also clamp manually below).
    this.sprite.setMaxVelocity(PhysicsConfig.maxSpeed, 2000);

    // --- DOUBLE JUMP STATE TRACKING ---
    this.jumpsUsed = 0;
    this.maxJumps = PhysicsConfig.doubleJumpEnabled ? 2 : 1;

    // Coyote-time / jump-buffer timers (ms).
    this.timeSinceGrounded = 9999;
    this.timeSinceJumpPressed = 9999;

    // Track whether we've "consumed" the current jump button press so
    // that holding the button doesn't auto-spam the double jump.
    this._bufferedJump = false;
  }

  update(delta) {
    const body = this.sprite.body;
    const dt = delta / 1000;
    const onGround = body.blocked.down;

    // ---------- Timers ----------
    this.timeSinceGrounded   = onGround ? 0 : this.timeSinceGrounded + delta;
    this.timeSinceJumpPressed += delta;

    // Reset double-jump count as soon as the player is on solid ground.
    if (onGround) this.jumpsUsed = 0;

    // ---------- HORIZONTAL MOVEMENT (TERRARIA-LIKE BASE VALUES) ----------
    const leftDown  = this.input.isLeft();
    const rightDown = this.input.isRight();

    // Air control reduces BOTH acceleration and friction so air movement
    // feels less grippy than ground movement but still responsive.
    const airMul   = onGround ? 1 : PhysicsConfig.airControlMultiplier;
    const accel    = PhysicsConfig.groundAccel    * airMul;
    const friction = PhysicsConfig.groundFriction * airMul;

    let vx = body.velocity.x;

    if (leftDown && !rightDown) {
      vx -= accel * dt;
    } else if (rightDown && !leftDown) {
      vx += accel * dt;
    } else {
      // No input: strong friction pulls velocity toward 0.
      if (vx > 0) vx = Math.max(0, vx - friction * dt);
      else if (vx < 0) vx = Math.min(0, vx + friction * dt);
    }

    vx = Phaser.Math.Clamp(vx, -PhysicsConfig.maxSpeed, PhysicsConfig.maxSpeed);
    body.setVelocityX(vx);

    // ---------- JUMP ----------
    // Jump buffer: if the player pressed jump slightly before landing,
    // remember it for a short window so the jump still fires on touchdown.
    if (this.input.isJumpJustDown()) {
      this.timeSinceJumpPressed = 0;
      this._bufferedJump = true;
    }

    const bufferedRecently = this.timeSinceJumpPressed <= PhysicsConfig.jumpBufferMs;
    const canCoyoteJump    = this.timeSinceGrounded   <= PhysicsConfig.coyoteTimeMs && this.jumpsUsed === 0;

    if (this._bufferedJump && bufferedRecently) {
      if (onGround || canCoyoteJump) {
        // First jump (ground or coyote).
        body.setVelocityY(PhysicsConfig.jumpVelocity);
        this.jumpsUsed = 1;
        this._bufferedJump = false;
        this.timeSinceJumpPressed = 9999;
      } else if (this.jumpsUsed < this.maxJumps) {
        // Mid-air double jump.
        body.setVelocityY(PhysicsConfig.doubleJumpVelocity);
        this.jumpsUsed++;
        this._bufferedJump = false;
        this.timeSinceJumpPressed = 9999;
      }
    }

    // Variable jump height: cut upward velocity when the player releases
    // the jump key early. Gives short taps for short hops.
    if (this.input.isJumpJustUp() && body.velocity.y < 0) {
      body.setVelocityY(body.velocity.y * PhysicsConfig.jumpCutMultiplier);
    }
  }

  // Used by CameraSystem + ProjectObject proximity checks.
  get x() { return this.sprite.x; }
  get y() { return this.sprite.y; }
  getPosition() { return { x: this.sprite.x, y: this.sprite.y }; }
}

window.Player = Player;
